### PR TITLE
Add alert.delay option, browser CLI flag

### PR DESCRIPTION
**Pull request by jweisman**
Hi @exlbashirn. I added an option to specify the browser when running `eca start`. Can you take a look and let me know if you see any issues with it? Thanks!

### CODE REVIEW

**Review by exlbashirn — APPROVED** [review]
I wonder if some indication re the browser names might be helpful for users, since it can be platform dependent.

Anyway, looks good.

**Comment by gpeterso** [comment]
@jweisman I know this has already been merged, but for the sake of consistency, may I suggest using two dashes for the option? 
(i.e `--browser` instead of `-browser`)

**Comment by jweisman** [comment]
Thanks all. 

@gpeterso - Good point. At first I thought that two dashes indicated a flag without a parameter, but that's not the case. So I updated it (it hasn't been released yet).

@exlbashirn - I also agree with this point. In the meantime the browsers are listed in the [documentation](https://developers.exlibrisgroup.com/cloudapps/docs/cli/#start) (at least as far as I could test on Mac and Windows). Any ideas as to how/whether to build this into the CLI?

**Comment by exlbashirn** [comment]
@jweisman I think just noting it the command description would be enough.

**Pull request merged**
